# Потом можем вынести конфигурационные файлы в отдельный репозиторий
networks:
    setkaNetwork:

services:
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        restart: always
        volumes:
            - './.next/:/usr/share/nginx/html/'
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
        networks:
            - setkaNetwork
        depends_on:
            - frontend

    certbot:
        image: certbot/certbot:latest
        volumes:
            - './certbot/www/:/var/www/certbot/:rw'
            - './certbot/conf/:/etc/letsencrypt/:rw'

    frontend:
        build: .
        ports:
            - 3000:3000
        networks:
            - setkaNetwork
