name: '[Setka.Client] Test build of the project'
on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
jobs:
    build:
        name: Test build
        runs-on: ubuntu-latest
        env:
            NODE_TLS_REJECT_UNAUTHORIZED: '0'

        steps:
            - name: git-checkout
              uses: actions/checkout@v4

            - name: pnpm-setup
              uses: pnpm/action-setup@v2

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build application
              run: pnpm run build
